---
- name: configure mutt for user
  hosts: mail
  become: true
  vars:
    owner:
      username: centos
      uid: 1010
    domain: "{{ lookup('env','DOMAIN') }}"
    #vpath: "/var/mail/vhosts"
    vpath: /var/spool/vmail
    vusers:
      - "info"
      - "sales"
    vdirs:

  tasks:
    - name: install mutt
      yum:
        name: mutt
        state: present
    
    - name: create .muttrc
      template: 
        src: muttrc.j2
        dest: "/home/{{ owner.username }}/.muttrc"

    - name: fix .muttrc permissions
      file:
        path: "/home/{{ owner.user }}/.muttrc"
        owner: "{{ owner.username }}"
        group: "{{ owner.username }}"
        mode: '0664'
