---
- name: update aws
  hosts: localhost
  become: true
  vars:
    domain: "{{ lookup('env','DOMAIN') }}"
    ip: "{{ lookup('env','IP') }}"
    aaki: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    asak: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

  tasks: 
    - name: add an spf txt-record
      route53:
        aws_access_key: "{{ aaki }}"
        aws_secret_key: "{{ asak }}"
        state: present
        zone: "{{ domain }}"
        record: "{{ domain }}"
        type: TXT
        overwrite: true
        value: '"v=spf1 ip4:{{ ip }} -all"'
