- name: install and configure postfix with virtual mailboxes
  hosts: mail
  become: true
  vars:
    version: postfix
    domain: "{{ lookup('env','DOMAIN') }}"
    vpath: "/var/mail/vhosts"
    owner: 
      username: centos
      uid: 1010
    vusers:
      - "info"
      - "sales"
    vdirs:
      [ "cur", "new", "tmp" ]
  tasks:
    - name: install postfix
      yum:
        name: "{{ version }}"
        state: present

    - name: open smtp
      firewalld: 
        zone: public
        service: smtp
        permanent: yes
        immediate: yes
        state: enabled

    - name: create main.cf
      template: 
        src: "main.cf.j2"
        dest: "/etc/postfix/main.cf"

    - name: create vmailbox
      template: 
        src: "vmailbox.j2"
        dest: "/etc/postfix/vmailbox"

    - name: create virtual
      template: 
        src: "virtual.j2"
        dest: "/etc/postfix/virtual"

    - name: create user
      user: 
        name: "{{ owner.username }}"
        uid: "{{ owner.uid }}"

    - name: create the virtual dir
      file:
        state: directory
        path: "{{ vpath }}/{{ domain }}"
        owner: root
        group: root
        mode: '0755'

    - name: create virtual maildir
      file: 
        state: directory
        path: "{{ vpath }}/{{ domain }}/{{ item[0] }}/{{ item[1] }}"
        owner: "{{ owner.username }}"
        group: "{{ owner.username }}"
        mode: '0755'
      with_nested:
        - "{{ vusers }}"
        - "{{ vdirs }}"

    - name: postmap /etc/postfix/vmailbox
      shell:
        cmd: postmap /etc/postfix/vmailbox

    - name: postmap /etc/postfix/virtual
      shell:
        cmd: postmap /etc/postfix/virtual

    - name: start and enable postfix
      systemd: 
        name: postfix
        state: started
        enabled: yes
